name: Deploy

on:
  workflow_run:
    workflows: [ "Build and Deploy" ]
    types:
      - completed
  workflow_dispatch:
  
jobs:
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps: 
      - name: Deploy to production
        uses: enwankwo/booklibraryapi@latest
        with:
           service-id: ${{ secrets.RENDER_SERVICE_ID }}
           api-key: ${{ secrets.RENDER_API_KEY }}
